### ISSUE TITLE
Handle invalid registration emails

### ISSUE THREAD

**Issue by ayumi** [brave/publishers#12]
It's possible for a user to:
1. Start a registration and enter an invalid email
2. Finish verification
3. Lose their session and be unable to resume because they welcome email was lost (sent to the invalid email.)

We could fix this by:
- Detect bad emails from 1 (via bounce HTTP webhook?). On bad email:
  - Option 0: Ask them to start a new registration.
  - Option 1: Show a website notification to the user, who probably still has an active session. (Roundtrip from publishers -> mailgun -> bounce -> publishers should take <1 min or up to 5 min)
  - Option 2: Send emails to the rfc {webmaster, hostmaster}@foo.example.com
  - Option 3: If they provided a phone number, call them / use Twilio to leave a recorded message saying their email is invalid, please enter this code to resume and update it.

@mrose17

**Comment by mrose17** [comment]
the only "legit" way to verify an email address is to send an email and ask them to click on a link that contains a stateful value and takes them back to the site. we need to do this.

@bradleyrichter - does this make sense to you? thanks!

**Comment by ayumi** [comment]
We're now requiring email verification so this is done.
