### ISSUE TITLE
sync with verification flow #2

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#20]
for discussion in a bit!

1. add email verification loop on page 4

2. add bifurcation page on page 5

3. add "Need help installing your text file?" popup on page 7

4. add popup on page 9. get the list of how to do this from @bradleyrichter, perhaps from googleapps/discourse instructions

5. indicate reason for failure (slides 10-11)

**Comment by ayumi** [comment]
added 1. and 2. Bifurcation / saving of verification method
