### ISSUE TITLE
for W-8BEN require either US TIN (box 5) or Foreign TIN (box 6)

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#23]
the accountants tell me that one must be supplied. is it possible to have docusign require one of those two boxes (both are OK, but one must be filled-in!)

for W-8BEN-E, either box 8 or box 9a (GIIN) or box 9b (Foreign TIN) is required.

thank you!

**Comment by mrose17** [comment]
update: this should be required ONLY if the filer is listing a US residence. if the address is not in the US then both boxes may be empty!

**Comment by ayumi** [comment]
currently we're not able to do conditional logic like part 2 ("only if the filer is listing a US residence")

and i think even part 1 requires a more advanced docusign account.

**Comment by mrose17** [comment]
OBE (BAT Mercury)
