### ISSUE TITLE
Add helper tooltip

### ISSUE THREAD

**Issue by jkup** [brave/publishers#27]
The DNS validation page should have a question mark helper tooltip. It is my understanding that @bradleyrichter has compiled a list of popular hosts and their DNS help pages that we can link to.

**Comment by bradleyrichter** [comment]
excel file for this lovely list:

[DNS_registrars_addTXT_records.xlsx](https://github.com/brave/publishers/files/640880/DNS_registrars_addTXT_records.xlsx)

**Comment by jkup** [comment]
@ayumi sending this one your way just to keep track! if you don't get time for it feel free to assign it back to me!
