### ISSUE TITLE
DNS verify form should work without JavaScript

### ISSUE THREAD

**Issue by bsclifton** [brave/publishers#43]
Per feedback https://github.com/brave/publishers/pull/39#pullrequestreview-12979047

The "Verify DNS Record" button uses JavaScript to show an interstitial "verifying..." page while the call is in progress.  If folks have JavaScript disabled, this form submission will not work.

We need to add a `<noscript>` block on this page which falls back to the previous behavior if JavaScript is not enabled (show a button which blocks until call is done). The JS enabled button can be set to display:none and have it's display set to "block" on page_load().

**Comment by dgeb** [comment]
Resolved via #105
