### ISSUE TITLE
Update intro page text to add info about bitcoin requirement

### ISSUE THREAD

**Issue by bradleyrichter** [brave/publishers#44]
New:

Welcome to Brave Payments
Brave users are already making contributions to thank you for your efforts. The first step toward collecting those contributions is to verify ownership of your web address so Brave users can see that your site is verified. Once fully verified, you will begin to receive daily micropayments in your Bitcoin wallet. 

Existing:

Welcome to Brave Payments
Brave users are already making contributions to thank you for your efforts. The first step toward collecting those contributions is to verify ownership of your web address so Brave users can see that your site is verified.

**Comment by mrose17** [comment]
@bsclifton - could you "make it so"?
