### ISSUE TITLE
the publisherID in all e-mails should to be in HTML

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#46]
see the two images below. the first one contains the email address as text, and the mail reader recognizes it as a URL and underlines it. the second one contains the email address as markup.

the issue is that some mail readers don't recognize all TLDs, so in some cases, the first one doesn't have the address automatically made into a link.

in all cases, for all messages, the publisherID should be a link, not a string

<img width="540" alt="1" src="https://cloud.githubusercontent.com/assets/400552/21404217/fcfc85b6-c774-11e6-9fe2-bfe3c6c62e23.png">
<img width="523" alt="2" src="https://cloud.githubusercontent.com/assets/400552/21404219/fec56782-c774-11e6-9e29-dd54f4fcee6c.png">

**Comment by dgeb** [comment]
Resolved via #98
