### ISSUE TITLE
Login tokens should expire

### ISSUE THREAD

**Issue by ayumi** [brave/publishers#51]
Every publisher has a secret URL which lets them manage their publisher registration. We added this to make it easy for publishers to bookmark and return to the management site.

[ThePythonicCow has noted in a Community post](https://community.brave.com/t/security-of-brave-publishers-payment-page-inadequate/378) that these private URLs don't expire, so if a third party discovers the link (for example, by forwarding a Publishers email, or posting it publicly) the publisher account would be compromised. This is a legit concern.

We'd like to:

0. Expire the secret URL token after use
*suggestion*: After verifying the login token and logging the publisher in, empty the token field.

1. Expire the secret URL token after some interval
*suggestion*: Add a new field, Publisher `#authentication_token_expires_at` and when we verify the token also verify the expires_at date.

2. For emails, ensure secret URL tokens are freshly generated right before each email is sent.

3. Add option to "Email me a login link"

@diracdeltas @mrose17

**Comment by diracdeltas** [comment]
that sounds good. also in emails and on the website, it should have a disclaimer to never publish or share the token.

**Comment by ThePythonicCow** [comment]
As noted above, I originated this concern a couple of months ago in a Community post.

"Secret" URL's are not an appropriate long term authentication mechanism, in my view, for any potentially high value resource.  They can be useful, for single-use, one-time, quickly expiring (say a day or less) checking that a newly provided email address works.  They can be useful for low value resources within controlled limitations, such as handing out read-only links to Amazon AWS S3 objects, which can be expired automatically, and which can be limited to the IP address of the user.

Some sort of real authentication method, classically involving at a minimum passwords that are never transmitted in the clear, never show plainly in a URL, and rarely sent via email, is needed to protect financial assets and identity (such as W-9 tax forms.)

Either I am seriously mistaken here, or else this "security" apparatus was never seen a competent security audit.  That seriously needs to happen.
