### ISSUE TITLE
Add type=hello to /notifications endpoint

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#52]
when the eyeshade server decides that it's time to notify a publisher that they have funds waiting for them, it will do a `POST /notifications/{address}?type=hello` call to to send a hello world message to the publisher.

**Comment by mrose17** [comment]
and don't forget to add instructions on doing the badge!

**Comment by ayumi** [comment]
related: #7

**Comment by alexwykoff** [comment]
closing in favor of https://github.com/brave/publishers/issues/7
