### ISSUE TITLE
Protocol on domain leads to error

### ISSUE THREAD

**Issue by jonathansampson** [brave/publishers#53]
While attempting to register a domain, one user reported that the presence of a protocol in the domain field yields a somewhat unhelpful error message. Perhaps we should detect protocols, in addition to having the example format in the input element's placeholder.

Report: https://twitter.com/OmgImAlexis/status/816163321711710208

**Comment by mrose17** [comment]
cf., https://github.com/brave/ledger-publisher#syntax for the syntax of a publisher identity

**Comment by dgeb** [comment]
Stripping the protocol could be done either entirely at the `ledger` endpoint (`/v2/publisher/identity`) or through a normalization step prior to sending the domain to `ledger`.

See the ["ledger offline"](https://github.com/brave/publishers/blob/master/app/services/publisher_domain_normalizer.rb#L30) code for an example of the latter.

**Comment by mrose17** [comment]
@dgeb - please do the latter... what gets sent to the ledger/eyeshade should conform to the syntax above...

**Comment by dgeb** [comment]
Resolved via #100.
