### ISSUE TITLE
Changes to wallet address must trigger email notification

### ISSUE THREAD

**Issue by da2x** [brave/publishers#59]
After setting a BitCoin payout address on the publisher portal, any change to that payout address should trigger an email notification about the change. The notification should contain the old and new wallet addresses, as well as the IP address that changed the payout address. 

I’ve changed all my wallet addresses several times without receiving any notification about it. Such notifications are part of a good security foundation where publishers can help notify Brave if any unauthorized changes are made to their account (the payout address being the most likely thing someone would want to change).

This also helps publisher keep a record of their active and historic wallet address.

**Comment by ayumi** [comment]
Thanks @da2x, I think this is a good idea.

**Comment by ayumi** [comment]
Fixed by #89, thanks @da2x!
