### ISSUE TITLE
Make phone number mandatory

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#61]
please 
![0](https://cloud.githubusercontent.com/assets/400552/22670729/66f77370-ec7f-11e6-939d-eef27bfeac06.png)
change the sign-up page to make the phone number mandatory...

**Comment by ayumi** [comment]
what's the reasoning behind this? initially we had a discussion about this and we concluded it should be optional.

**Comment by mrose17** [comment]
a phone number is required for most KYC (know your customer) APIs. you don't have to answer the phone, but you do need to provide a number that is (somehow) associated with you. that appears to be a regulatory necessity.

**Comment by ayumi** [comment]
that makes sense for paying people, but maybe a user just wants the ✅ for now. in that case, do you suggest they put "1-800-123-4567"?

**Comment by mrose17** [comment]
as with all things, i suggest that folks enter accurate and correct information...
