### ISSUE TITLE
Determine funnel conversion rates for site verification

### ISSUE THREAD

**Issue by ayumi** [brave/publishers#65]
On the publishers site, you can verify your site with manual guidance or with DNS. We'd like to know the rates of publishers going through each step of the process. We might be able to derive these from server access logs, which are stored on Papertrail via Heroku.

- Verify email
- Guided onboarding
- Opt for DNS; and succeed
- Opt for DNS; but give up (We could improve this case with better UX)

@mrose17 @alexwykoff @BrendanEich

**Comment by mrose17** [comment]
https://github.com/brave/publishers/issues/16 is a pre-requisit for this, i suspect.

**Comment by ayumi** [comment]
"Opt for DNS; and giving up" might be doable currently. We'd check that the same IP visits the DNS page but doesn't visit subsequent pages.

**Comment by alexwykoff** [comment]
closing this in favor of https://github.com/brave/publishers/issues/16
