### ISSUE TITLE
get website ranking (from a service) when a publisher entry is created

### ISSUE THREAD

**Issue by mrose17** [brave/publishers#67]
the goal here is to help prioritize the triage queue.

**Comment by alexwykoff** [comment]
mr : is still still an issue and if so, how should we go about it?

aw : i think this has more benefit for bizdev and pr if we're bringing back text

mr : i think we should use alexa, put the score into db and into the email which goes to publisher managers

aw : shouldn't this be an eyeshade issue?

bc : i agree if not customer facing

mr : yes, let's move it to eyeshade

to summarize : closing here to implement in eyeshade
