### ISSUE TITLE
Publishers need various email nudges to have them complete the flow

### ISSUE THREAD

**Issue by alexwykoff** [brave/publishers#84]
We send a series of manual emails to users to help them through the flow. 

We would like to move these to an automation system because they are boilerplate and time consuming.

**Comment by mrose17** [comment]
one we need is discussed here: https://github.com/brave/publishers/issues/52 -- to allow the ledger to ask publishers to send a note to a publisher indicating that they have BTC waiting and they ought to verify.

**Comment by alexwykoff** [comment]
closing in favor of https://github.com/brave/publishers/issues/7
